apiVersion: apps/v1
kind: Deployment
metadata:
  name: hands-on6-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hands-on6
  template:
    metadata:
      labels:
        app: hands-on6
    spec:
      containers:
      - name: hands-on6repos
        image: samplecr.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: hands-on6
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hands-on6